apiVersion: v2
name: rada
description: A Helm chart for Rada Bitcoin to M-PESA payment system
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: redis
    version: "17.3.7"
    repository: "https://charts.bitnami.com/bitnami"
  - name: postgresql
    version: "12.1.6"
    repository: "https://charts.bitnami.com/bitnami"
  - name: prometheus
    version: "15.10.1"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: monitoring.enabled
  - name: grafana
    version: "6.50.7"
    repository: "https://grafana.github.io/helm-charts"
    condition: monitoring.enabled
