apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rada-api-monitor
  namespace: ${ENVIRONMENT}
spec:
  selector:
    matchLabels:
      app: rada-api
  endpoints:
  - port: metrics
    interval: 15s
    path: /metrics

---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rada-alerts
  namespace: ${ENVIRONMENT}
spec:
  groups:
  - name: rada.rules
    rules:
    - alert: HighErrorRate
      expr: |
        sum(rate(http_requests_total{status=~"5.."}[5m])) 
        / 
        sum(rate(http_requests_total[5m])) > 0.05
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: High error rate detected
        description: Error rate is above 5% for the last 5 minutes

    - alert: HighLatency
      expr: |
        histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le)) > 2
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: High latency detected
        description: 95th percentile latency is above 2 seconds

    - alert: HighMemoryUsage
      expr: |
        container_memory_usage_bytes{container="rada-api"} 
        / 
        container_spec_memory_limit_bytes{container="rada-api"} > 0.85
      for: 15m
      labels:
        severity: warning
      annotations:
        summary: High memory usage
        description: Container memory usage is above 85% for 15 minutes

    - alert: HighCPUUsage
      expr: |
        sum(rate(container_cpu_usage_seconds_total{container="rada-api"}[5m])) 
        / 
        sum(container_spec_cpu_quota{container="rada-api"} / 100000) > 0.85
      for: 15m
      labels:
        severity: warning
      annotations:
        summary: High CPU usage
        description: Container CPU usage is above 85% for 15 minutes

    - alert: DatabaseConnections
      expr: |
        pg_stat_activity_count{datname="rada"} > 80
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: High number of database connections
        description: Database connection count is high

    - alert: RedisMemoryUsage
      expr: |
        redis_memory_used_bytes / redis_memory_max_bytes > 0.85
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: High Redis memory usage
        description: Redis memory usage is above 85%

    - alert: SSLCertExpiry
      expr: |
        (ssl_certificate_expiry_seconds - time()) / 86400 < 30
      for: 1h
      labels:
        severity: warning
      annotations:
        summary: SSL Certificate expiring soon
        description: SSL Certificate will expire in less than 30 days

    - alert: PodRestarts
      expr: |
        increase(kube_pod_container_status_restarts_total{container="rada-api"}[1h]) > 2
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: Frequent pod restarts
        description: Pod has restarted more than 2 times in the last hour
